apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      service: shopping
  template:
    metadata:
      labels:
        service: shopping
    spec:
      containers:
        - image: shopping
          name: shopping
          ports:
            - containerPort: 50051
              protocol: TCP
            - containerPort: 3000
              protocol: TCP
          resources: {}
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
status: {}
