# Stage 1: build the monorepo
FROM node:12-slim

# Set to a non-root built-in user `node`
USER node

# Create app directory (with user `node`)
RUN mkdir -p /home/node/app

WORKDIR /home/node/app

# Bundle app source code
COPY --chown=node package.json lerna.json tsconfig.json ./
COPY --chown=node packages ./packages
RUN npm install && npm run build
